### ISSUE TITLE
No tool or SDK found by name 'sdk-upstream-incoming-64bit'.

### ISSUE THREAD

**Issue by cucibala** [emscripten-core/emsdk#727] opened 2021-02-24 09:04 UTC
follow[https://www.wasm.com.cn/getting-started/developers-guide/](url)i can't init environment
![Uploading image.png…]()

**Comment by sbc100** [comment] 2021-02-24 16:31
I think if you replace "incoming" with "master" it will work.

However you probably don't want to install from source... its better to just do `emsdk install latest` which will give you pre-compiled binaries.

**Comment by cucibala** [comment] 2021-02-25 01:42
when i use ./emsdk install latest ,it still not work throw "Error: No tool or SDK found by name 'sdk-releases-upstream-fc5562126762ab26c4757147a3b4c24e85a7289e-64bit'."

**Comment by sbc100** [comment] 2021-02-25 16:31
That is very strange, what platform are you using?

**Comment by anmolsud** [comment] 2021-02-26 11:11
I get a similar error when trying to do this on M1 Mac. I'm guessing that's because of missing support for M1, maybe.

**Comment by sbc100** [comment] 2021-02-26 16:35
Closing a duplicate of https://github.com/emscripten-core/emsdk/issues/671.  We can re-open if this is a separate issue.

**Closed by sbc100** 2021-02-26 16:35 UTC
