### ISSUE TITLE
Cannot execute compiled files in Chrome.

### ISSUE THREAD

**Issue by shogerr** [emscripten-core/emsdk#259] opened 2019-06-02 15:43 UTC
1. Git clone.
2. emsdk install latest
3. emsdk activate latest
4. em++ test/hello.cpp -o hello.html (simply printf with hello world)

Open html file in Chrome, and emscripten continually says "downloading" or "preparing" and never loads.

No debug or information to resolve fix this issue presented on screen or in the developer tools Chrome provided (ie, no console warnings or messages).

Remove and re-download emsdk: same error.

Only thing that might help is:
```
> em++ -v
shared:ERROR: Emscripten, llvm and clang build versions do not match, this is dangerous (1.38.33, 1.38.31, 1.38.31)
shared:ERROR: Make sure to rebuild llvm and clang after updating repos
```

I tried building from source, but it fails on Windows, with an error about a zip file already present. This also happens when you try to upgrade an old version of emsdk on Windows.

**Comment by kripken** [comment] 2019-06-02 16:13
The warning should be fixed by #258 that I merged just now. I think it's unrelated to the other problem you have, though. Are you perhaps loading an HTML using a file:// URL in chrome? That will fail to load the wasm file due to how chrome handles permissions, so you need to run a webserver (like `python -m SimpleHTTPRequest`).

**Comment by kripken** [comment] 2019-06-02 16:13
If that's not it, please attach the output files (html, js, wasm) and I'll see if I can reproduce and debug it.

**Comment by shogerr** [comment] 2019-06-02 16:35
@kripken, thanks for the fast reply. I am cloning the emsdk repo again, and will be providing output shortly.

I guess my biggest shortcoming in tackling this is not knowing where I should be looking for errors when something like this happens.

**Comment by kripken** [comment] 2019-06-02 16:56
I think you did the right thing, the right place to look for errors is in the developer tools (both dev console and network tab), on the web page itself, and also when you run a webserver, in the webserver's output.

The file:// issue in chrome is annoying since it may not log anything in the devtools. However, I think the page itself should report a failure to load the wasm file.

**Comment by shogerr** [comment] 2019-06-02 17:11
Alright, report time.

After reinstalling emsdk:
- I no longer receive the error about clang and llvm version mismatch, so awesome.
- The project compiles fine and produces the files expected.
- The output .html runs fine in Firefox without an http server;
- but it will not run in Chrome (same result with it hanging) out-of-the-box.

So, per your suggestion, I ran `python -m SimpleHTTPServer` (small typo in your example), and then visited `http://localhost:8000/hello.html` in Chrome, and everything worked! So thanks : )

I also tested `emrun --no_browser --port 8080 .`, and this also works. I will point out that you cannot use the `ctrl+c` signal to kill this process from Powershell 6, and must manually kill the process to end the service.

I would close the issue, as I feel it's resolved, however, maybe this warrants a PR to the documentation for Chrome users? Or maybe better output on errors as you suggested in the last comment? So I'll let you close the issue.

Thanks again!

**Comment by kripken** [comment] 2019-06-04 17:18
Thanks, yeah, I opened https://github.com/emscripten-core/emscripten/pull/8734 to improve the docs.

**Closed by kripken** 2019-06-04 17:18 UTC

**Comment by JonathanSum** [comment] 2021-06-05 16:35
I use the expressjs to set up a localhost:3000 server , and it stalls in the downloading page.

**Comment by bank2014** [comment] 2023-08-25 14:45
python -m http.server 80    works on the newer versions of Python
