### ISSUE TITLE
`emsdk activate latest --global` fails on Windows for want of PyWin32

### ISSUE THREAD

**Issue by gjm-lbo** [emscripten-core/emsdk#458] opened 2020-03-27 13:56 UTC
After the following (on Windows 10; systemwide-installed Python version is 3.8.2)

    git clone https://github.com/emscripten-core/emsdk.git
    cd emsdk
    git pull
    emsdk install latest
    emsdk activate latest

(all of which appears to work fine), the further step

    emsdk activate latest --global

fails with the following message:

    ERROR: The system was unable to find the specified registry key or value.
    Failed to import Python Windows extensions win32api and win32con.
    Make sure you are using the version of python available in emsdk,
    or install PyWin extensions to the distribution of Python you are attempting to use.
    (This script was launched in python instance from "[my emsdk dir]\python\3.7.4_64bit\python.exe")

Installing PyWin32 for my global Python installation doesn't change this in any way, unsurprisingly given the last bit of that message.

"Aha", I thought, "I'll just run the appropriate version of the PyWin32 installer and point it at the Python directory inside emsdk". But I can't do that because there _isn't_ really a Python directory inside emsdk, just a directory containing lots of individual executables and libraries and whatnot. Normally PyWin32 lives in a bunch of directories inside `Lib\site-packages` but there's neither a `Lib` nor a `site-packages` in the emsdk python directory.

I can live without `activate latest --global`, of course, but suppose I wanted it to work. Is there anything I could do? E.g., would downgrading my system Python from 3.8.2 to 3.7.4, the version inside emsdk, help? Or would creating some suitable structure of directories under `python\3.7.4_64bit` make it possible to install PyWin32 there?

----

It looks as if maybe just deleting the `python\3.7.4_64bit` directory in emsdk might do the job because then emsdk would fall back to using the system Python installation. But I'm reluctant to do that given that `emsdk install` _deliberately creates and populates_ that directory even though I already have a perfectly good Python installation. Still, I tried just in case (I actually renamed the directory rather than removing it) and got some different errors; I don't know whether they're consequences of using a "wrong" Python or not; it looks to my inexpert eye as if they probably aren't, in which case presumably they should be a separate issue; but here they are just in case:

    Failed to read environment variable EMSDK_NODE:
    'EMSDK_NODE'
    Failed to read environment variable EMSDK_NODE:
    'EMSDK_NODE'
    ERROR! Failed to set environment variable 
    EMSDK_NODE=[my emsdk dir]/node/12.9.1_64bit/bin/node.exe:
    (1159, 'PostMessage', 'The message can be used only with synchronous operations.')
    You may need to set it manually.
    ERROR: The system was unable to find the specified registry key or value.
    ERROR! Failed to set environment variable 
    JAVA_HOME=[my emsdk dir]/java/8.152_64bit:
    (1159, 'PostMessage', 'The message can be used only with synchronous operations.')
    You may need to set it manually.
    ERROR! Failed to set environment variable PATH=[lengthy PATH value]:
    (1159, 'PostMessage', 'The message can be used only with synchronous operations.')
    You may need to set it manually.

(It looks as if those variables _have_ in fact been set, at least in the cmd window from which I ran the emsdk commands and in Windows's environment variables dialog, so my guess is that what's failing is the `win32api.PostMessage(win32con.HWND_BROADCAST, win32con.WM_SETTINGCHANGE, 0, 'Environment')` call at the end of `win_set_environment_variable_direct`.)

**Comment by SK83RJOSH** [comment] 2020-04-10 14:06
I can confirm with an identical install of Python that I get the same warnings and errors. It seems in that directory you'll find a Python37.zip with the full install, by the way. I guess the extract only the bare minimum -- and entirely miss PyWin32 in the process?

**Comment by keithpenney** [comment] 2020-04-20 21:29
In case anyone needs a workaround, this was an annoying process, but it worked for me.  I first tried copying the `pywin32` install from my system-wide Python instance, but quickly realized the compiled dlls were incompatible (my Python preferred install was 3.6 32-bit).  And to complicate matters further, the embedded 3.7 version that ships with `emsdk` is bare-bones (no `setuptools` or `pip` included).  And it turns out `pywin32` is a pretty complicated package due to its support for many versions of Windows/Python and its system-level access requirements.  Therefore, I couldn't just download the dlls I needed - I had to do the following:

- Download and install Python 3.7 (64-bit) if not already installed 

- Install `pywin32` via the 3.7 (64-bit) instance (either via `pip` or from the corresponding release on github).

- Copy the following items into your `emsdk` python installation folder (i.e. `...\emsdk\python\3.7.4_64bit\` ) from your system-wide python 3.7 (64-bit) installation (i.e. `...\Python37\Lib\site-packages\` ).

    - `win32`, `win32com`, `win32comext`, `pywin32_system32`, `pythoncom.py`

`emrun` should now have all pywin32 dependencies met, though I haven't put it through any real rigorous testing - just a hello world.

I haven't dug deeply through `emrun.py`, but I wonder if it would be worth the effort to try to remove the dependence on `pywin32` if possible.

**Comment by sbc100** [comment] 2020-05-04 18:09
Could you all please confirm that this issue is now fixed?

**Closed** 2020-05-04 18:09 UTC

**Comment by gjm11** [comment] 2020-05-04 19:36
I no longer get the same error when I say `emsdk activate latest --global`. I get different errors instead, which look like the same ones as I reported earlier. So it looks as if this particular issue is fixed, but the other errors may still need investigating.

**Comment by keithpenney** [comment] 2020-05-04 21:11
No errors on my end.  I just started with a fresh clone and was able to install and activate without any modifications.
Windows 10 (10.0.18362) Pro on x64-based CPU.
