### ISSUE TITLE
llvm-link missing since 2.0.30

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emsdk#914] opened 2021-10-19 07:59 UTC
@dschuff @sbc   llvm-link is missing since 2.0.30.

See #866 for a discussion why some people (including me :) ) need it.

**Comment by sbc100** [comment] 2021-10-19 16:48
Basically we now build two versions of the emsdk binaries, one is called e.g. `2.0.31` and one is called e.g. `2.0.31-assert`.   The default one is built with LTO and we currently fail to ship llvm-link.   Installing `2.0.31-asserts` should fix the issue until #866 is fixed.

Do you want to keep this duplicate issue open or are you ok with closing it as a duplicate of #866 (I feel like one of them clearly should be closed because they are the same issue).

**Closed as completed** 2021-10-19 16:51 UTC
