### ISSUE TITLE
temporarily removing tools from the PATH

### ISSUE THREAD

**Issue by bakkot** [emscripten-core/emsdk#1074] opened 2022-07-17 20:53 UTC
I see that there's an [open issue](https://github.com/emscripten-core/emsdk/issues/1064) about vendoring a more recent version of `node`, and that this is not something you're currently planning on (though do note that v14 goes EOL on 2023-04-30).

If a project has other dependencies which require a later version of node, the older version of node causes problems. And it's quite hard to juggle multiple versions in CI, particularly since `emsdk uninstall node` doesn't work - you have to name the specific version which is installed, which there does not appear to be a trivial way to automatically determine.

So is there a way to get emsdk to remove its tools from the PATH (without uninstalling them) so that you can run the system version of `node`?

**Comment by sbc100** [comment] 2022-07-17 21:01
One easy fix it simply put your version node first in the PATH (after activating emsdk).

There are efforst at a better soution but they are not currently making much progress.  See https://github.com/emscripten-core/emscripten/issues/4848 and https://github.com/emscripten-core/emsdk/pull/714 for more discussion on this.

**Comment by sbc100** [comment] 2022-07-17 21:02
I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/4848.. if its ok with you we can close as a dup of that?

**Comment by bakkot** [comment] 2022-07-17 21:29
> One easy fix it simply put your version node first in the PATH (after activating emsdk).

That's not trivial to do in CI, but I guess it's probably possible. I assume emsdk will still use its vendored version of node, in that case?

> I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/4848.. if its ok with you we can close as a dup of that?

That issue is currently closed? If you want to reopen that issue and close this as a duplicate I'm fine with that, but I'd like it to be tracked as an open issue somewhere.

**Comment by sbc100** [comment] 2022-07-17 22:52
Yes, emscripten will always use the vendors version of node internally, regardless of the PATH.

**Comment by sbc100** [comment] 2022-07-17 22:56
Closing in favor of re-opened https://github.com/emscripten-core/emscripten/issues/4848

**Closed by sbc100** 2022-07-17 22:56 UTC
