### ISSUE TITLE
ARM and ARM64 Docker images 

### ISSUE THREAD

**Issue by pinguin999** [emscripten-core/emsdk#1000] opened 2022-03-15 09:57 UTC
Hi 

the docker image for emscripten/emsdk based on the Ubuntu image and that's available as ARM and ARM64 dockers.

Is it possible to also get the emscripten/emsdk image as ARM and ARM64?

**Comment by sbc100** [comment] 2022-03-15 14:45
I think this is duplicate of #547. 

We don't build official emsdk binaries for linux/arm or linux/arm64, but there is discussion of adding a way for the community to support this somehow.

**Comment by sbc100** [comment] 2022-03-16 18:57
Closing as duplicate, please re-open if you disagree.

**Closed by sbc100** 2022-03-16 18:57 UTC

**Comment by Alexhuszagh** [comment] 2022-08-01 19:30
> Closing as duplicate, please re-open if you disagree.

Just adding that there's a difference between supporting an ARM64 image and providing one (IE, having multiple architectures on Docker Hub). I understand if you want to support the former but not provide the latter.

**Comment by reinhrst** [comment] 2023-11-04 04:07
For people coming here hoping to find a Arm64 Docker image, I'm happy to share [this gist](https://gist.github.com/reinhrst/84b9e20a8a68bcd0e3a48065fc2b9bf3)
